### ISSUE TITLE
Doesn't seem to install

### ISSUE THREAD

**Issue by jonjitsu** [kovan/dopemacs#3]
Cool project but it doesn't seem to install.

I tried with:
 git clone https://github.com/kovan/dopemacs.git .emacs.d

and running emacs a few times like the readme suggested.

One of the errors:
Debugger entered--Lisp error: (error "Package `anchored-transpose-' is unavailable")

I also tried:
 git clone https://github.com/kovan/dopemacs.git .emacs.d
git checkout 1.0

and running emacs a few times like the readme suggested.

One of the errors:
mapc: Cannot open load file: no such file or directory, helm-match-plugin

**Comment by kovan** [comment]
Fixed
